### ISSUE TITLE
.Rprofile gargle options

### ISSUE THREAD

**Issue by behrman** [dcl-docs/wrangle#3]
For `options(gargle_oauth_cache = ) `, I believe that instead of the path to the gargle token, users need to provide the path to the gargle oauth cache _directory_. The example would be `"~/.R/gargle/gargle-oauth"`.

Also, readers may be confused  by "your Google email". Some may interpret this to be their personal Gmail account. Perhaps "your Google account email".

    options(
      gargle_oauth_cache = "GARGLE_OAUTH_DIR",
      gargle_oauth_email = "YOUR_GOOGLE_ACCOUNT_EMAIL"
    )

**Comment by skaltman** [comment]
It only works for me to have the path to the token, although now I see that the documentation does say path to the folder...

**Comment by skaltman** [comment]
Never mind, I think I figured it out. Somehow I had two gargle-oauth directories in gargle. I just removed one and now it works.
